[project]
name = "train-d4rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cython<3",
    "d4rl>=1.1",
    "distrax>=0.1.5",
    "flax>=0.10.7",
    "gym==0.23.1",
    "gymnasium>=1.2.2",
    "jax[cuda12]==0.6.2",
    "minari[hf]>=0.5.3",
    "numpy>=2",
    "orbax-checkpoint>=0.11.25",
    "orbax-export>=0.0.8",
    "wandb>=0.23.0",
    "tqdm>=4.66.0",
    "ogbench>=1.2.0",
    "chex>=0.1.90",
    "simple-parsing>=0.1.7",
]
